export const fakeTeams = [
  "Team 1",
  "Team 2",
  "Team 3",
  "Team 4",
  "Team 5",
  "Team 6",
  "Team 7",
  "Team 8",
  "Team 9",
  "Team 10",
  "Team 11",
  "Team 12",
  "Team 13",
  "Team 14",
  "Team 15",
  "Team 16",
  "Team 17",
  "Team 18",
  "Team 19",
  "Team 20",
];

export const fakeLeague = [
  "Ligue 1",
  "Premier League",
  "Serie A",
  "Liga",
  "Bundesliga",
  "Champions League",
];

export const fakePlayers = [
  {
    name: "Cristiano Ronaldo",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Lionel Messi",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Zinedine Zidane",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Sadio Mané",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Mohammed Salah",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Bob Dylan",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Djobi Djoba",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Marco Verrati",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Marilyn Manson",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "René Coti",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Jacques Chirac",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Marie Curie",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Tony Kroos",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "George Orwell",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "James Bond",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Jimi Hendrix",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Janis Joplin",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Alexandre Le Grand",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Vercingétorix",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Noël Flantier",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Pelé",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Zlatan Ibrahimovic",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Franck Ribéry",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Kylian Mbappé",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
  {
    name: "Antoine Griezmann",
    goals: Math.floor(Math.random() * 500),
    league: fakeLeague[Math.floor(Math.random() * 6)],
    team: fakeTeams[Math.floor(Math.random() * 20)],
  },
];
